from pycsdr.modules import Module, Writer
from typing import List

version: str = ...
csdreti_version: str = ...


class EtiDecoder(Module):
    def __init__(self):
        ...

    def setMetaWriter(self, writer: Writer) -> None:
        ...

    def setServiceIdFilter(self, services: List[int]) -> None:
        ...
